name: Convert SUD(s) to WAV(s)
on:
  push:
    branches:
      - main
      - 'input/**' # Trigger on pushes to the input_sud_files directory
jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    - name: Build Docker image
      run: docker build -t sud_to_wav_converter .
    - name: List input files
      run: ls -l ${{ github.workspace }}/input_sud_files
    - name: Run conversion script
      run: docker run --rm -v ${{ github.workspace }}/input_sud_files:/workspace/input_sud_files -v ${{ github.workspace }}/output_wav_files:/workspace/output_wav_files sud_to_wav_converter /workspace/scripts/convert_files.sh
    - name: List output files
      run: ls -l ${{ github.workspace }}/output_wav_files
    - name: Change file permissions
      run: sudo chown -R $USER:$USER ${{ github.workspace }}/output_wav_files
    - name: Configure Git identity
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
    - name: Commit and push output files
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        DATE_TIME=$(date +'%Y-%m-%d_%H-%M-%S')
        BRANCH_NAME="output-${DATE_TIME}"
        git checkout --orphan $BRANCH_NAME  # Create a new orphan branch
        git reset --hard  # Remove all files from the working directory
        cp -r output_wav_files /tmp/output_wav_files_copy  # Copy output files to a temporary location
        git clean -fdx  # Remove all untracked files from the working directory
        mv /tmp/output_wav_files_copy output_wav_files  # Move the output files back
        git add output_wav_files  # Add only the output files
        git commit -m 'Add converted wav files'
        git push --force "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}" $BRANCH_NAME
